"""Generates the eXPoSe SpectraDeck user manual as a .docx file.

Content is condensed and adapted from README.md into manual-style prose.
Every place a screenshot would help the reader gets a bordered placeholder
box plus a numbered caption, so finishing the manual is just: open it in
Word, click a placeholder, Insert > Picture (or drag a screenshot in).

Run with the interpreter that has python-docx installed:
    python manual/build_manual.py
"""

import datetime
import os
import sys

FIGDIR = os.path.join(os.path.dirname(__file__), "figures")
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import appinfo

from docx import Document
from docx.enum.table import WD_ROW_HEIGHT_RULE
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor

OUTPUT = os.path.join(os.path.dirname(__file__), "eXPoSe_SpectraDeck_Manual.docx")

APP_NAME = appinfo.NAME
APP_VERSION = appinfo.VERSION

ACCENT = RGBColor(0x2C, 0x3E, 0x50)  # matches pdfstyle.py's default navy accent
GREY = RGBColor(0x80, 0x80, 0x80)

fig_counter = {"n": 0}


# ----------------------------------------------------------------------
# low-level helpers
# ----------------------------------------------------------------------

def shade_cell(cell, hex_fill):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_fill)
    tcPr.append(shd)


def add_field(paragraph, instr_text, placeholder_text=""):
    """Insert a raw OOXML field code (TOC, PAGE, NUMPAGES, ...) into a run."""
    run = paragraph.add_run()
    r = run._r

    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")

    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = instr_text

    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")

    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")

    r.append(begin)
    r.append(instr)
    if placeholder_text:
        t = OxmlElement("w:t")
        t.text = placeholder_text
        r.append(separate)
        r.append(t)
    else:
        r.append(separate)
    r.append(end)
    return run


def set_page_a4(doc, margin_cm=2.2):
    section = doc.sections[0]
    section.page_width = Cm(21.0)
    section.page_height = Cm(29.7)
    section.left_margin = Cm(margin_cm)
    section.right_margin = Cm(margin_cm)
    section.top_margin = Cm(1.8)
    section.bottom_margin = Cm(1.8)


def add_footer(doc):
    section = doc.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(f"{APP_NAME} — User Manual  ·  Page ")
    run.font.size = Pt(9)
    run.font.color.rgb = GREY
    add_field(p, "PAGE", "1")
    run2 = p.add_run(" of ")
    run2.font.size = Pt(9)
    run2.font.color.rgb = GREY
    add_field(p, "NUMPAGES", "1")
    for r in p.runs:
        r.font.size = Pt(9)
        r.font.color.rgb = GREY


# ----------------------------------------------------------------------
# content-building helpers
# ----------------------------------------------------------------------

def h1(doc, text):
    doc.add_heading(text, level=1)


def h2(doc, text):
    doc.add_heading(text, level=2)


def para(doc, text):
    doc.add_paragraph(text)


def bullets(doc, items):
    for item in items:
        doc.add_paragraph(item, style="List Bullet")


def add_table(doc, headers, rows, widths_cm=None):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    table.autofit = False
    hdr_cells = table.rows[0].cells
    for i, text in enumerate(headers):
        hdr_cells[i].text = ""
        r = hdr_cells[i].paragraphs[0].add_run(text)
        r.bold = True
        r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        shade_cell(hdr_cells[i], "2C3E50")
        if widths_cm:
            hdr_cells[i].width = Cm(widths_cm[i])
    for row in rows:
        cells = table.add_row().cells
        for i, text in enumerate(row):
            cells[i].text = str(text)
            if widths_cm:
                cells[i].width = Cm(widths_cm[i])
    doc.add_paragraph()
    return table


def add_figure(doc, caption, height_cm=6.0, image_path=None, width_cm=16.6):
    """A numbered figure.

    With ``image_path`` (a file under ``figures/``, generated by
    build_illustrations.py) the real picture is embedded directly. Without
    one, a bordered, shaded placeholder box is left instead: delete its
    text and Insert > Picture (or drag a screenshot in) to finish it.
    """
    fig_counter["n"] += 1
    n = fig_counter["n"]

    if image_path and os.path.isfile(image_path):
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.add_run().add_picture(image_path, width=Cm(width_cm))
        cap = doc.add_paragraph()
        cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
        cap_run = cap.add_run(f"Figure {n}. {caption}")
        cap_run.italic = True
        cap_run.font.size = Pt(10)
        doc.add_paragraph()
        return

    table = doc.add_table(rows=1, cols=1)
    table.style = "Table Grid"
    table.autofit = False
    row = table.rows[0]
    row.height_rule = WD_ROW_HEIGHT_RULE.AT_LEAST
    row.height = Cm(height_cm)
    cell = row.cells[0]
    cell.width = Cm(16.6)
    shade_cell(cell, "F2F2F2")

    cell.paragraphs[0].text = ""
    p1 = cell.add_paragraph()
    p2 = cell.paragraphs[1] if len(cell.paragraphs) > 1 else cell.add_paragraph()
    p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p2.add_run(f"[ Insert screenshot here — {caption} ]")
    run.italic = True
    run.font.size = Pt(11)
    run.font.color.rgb = GREY
    cell.add_paragraph()

    cap = doc.add_paragraph()
    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    cap_run = cap.add_run(f"Figure {n}. {caption}")
    cap_run.italic = True
    cap_run.font.size = Pt(10)
    doc.add_paragraph()


def add_page_break(doc):
    doc.add_page_break()


# ----------------------------------------------------------------------
# title page and table of contents
# ----------------------------------------------------------------------

def build_title_page(doc):
    for _ in range(4):
        doc.add_paragraph()
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = title.add_run(APP_NAME)
    r.bold = True
    r.font.size = Pt(40)
    r.font.color.rgb = ACCENT

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = subtitle.add_run("User Manual")
    r.font.size = Pt(20)
    r.font.color.rgb = GREY

    doc.add_paragraph()
    version_p = doc.add_paragraph()
    version_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = version_p.add_run(f"Covers version {APP_VERSION}  ·  {datetime.date.today():%d %B %Y}")
    r.font.size = Pt(11)
    r.font.color.rgb = GREY

    doc.add_paragraph()
    doc.add_paragraph()
    table = doc.add_table(rows=1, cols=1)
    table.style = "Table Grid"
    table.autofit = False
    row = table.rows[0]
    row.height_rule = WD_ROW_HEIGHT_RULE.AT_LEAST
    row.height = Cm(7.0)
    cell = row.cells[0]
    cell.width = Cm(16.6)
    shade_cell(cell, "F2F2F2")
    cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = cell.paragraphs[0].add_run(
        "[ Insert your logo or a hero screenshot of the application here ]"
    )
    run.italic = True
    run.font.color.rgb = GREY

    add_page_break(doc)


def build_toc(doc):
    heading = doc.add_paragraph()
    r = heading.add_run("Table of Contents")
    r.bold = True
    r.font.size = Pt(24)
    r.font.color.rgb = ACCENT
    doc.add_paragraph()

    p = doc.add_paragraph()
    add_field(
        p,
        'TOC \\o "1-2" \\h \\z \\u',
        "Right-click here and choose “Update Field” "
        "(or press F9) to build the table of contents.",
    )
    add_page_break(doc)


# ----------------------------------------------------------------------
# chapter content
# ----------------------------------------------------------------------

FORMATS_HEADERS = ["Format", "Extension", "Notes"]
FORMATS_ROWS = [
    ("VAMAS (ISO 14976)", ".vms, .vamas",
     "From any vendor (Kratos/CasaXPS, PHI, SPECS, Thermo, ...). Handles "
     "NORM/MAP/SDPSV modes, regular and irregular scans, and vendor comment blocks."),
    ("Thermo Avantage text dump", ".avg (.avx text dump)",
     "Multi-position scans give one region per position; a SnapMap loads as its "
     "summed spectrum; camera images become pictures, not spectra."),
    ("Thermo Avantage binary", ".vgd (.avx binary)",
     "Reverse-engineered container; matches the .avg of the same data exactly."),
    ("Thermo Avantage experiment", "a folder, or .VGX",
     "Opens the whole experiment as one session: samples, analysis points, scans in "
     "run order, camera images and SnapMaps (Chapter 22)."),
    ("PHI / ULVAC-PHI MultiPak", ".spe", "Intensities are counts per second, as stored."),
    ("Scienta Omicron SES", ".txt", "Detector/angle columns are summed to one spectrum."),
    ("Kratos Vision2 dataset", ".dset",
     "The binary file Vision2 writes, read directly without the DumpDataset step. Gives the "
     "same spectra and settings as its .kal. A setting the reader has not met before is left "
     "out with a warning rather than guessed."),
    ("Kratos Vision", ".kal",
     "Includes the transmission function. Files that do not record the X-ray "
     "source stay on a kinetic-energy axis (a warning says so)."),
    ("Kratos ESCApe", ".experiment", "Undocumented binary container; best-effort reverse engineering."),
    ("KherveFitting project", ".kfit",
     "HDF5 project file (needs the optional h5py). Loads the spectra with the fits, "
     "backgrounds and sensitivity factors KherveFitting stored. A standalone Peaks "
     "Library .json is opened separately: Tools → Import KherveFitting peak model…"),
]

LAUNCH_FLAGS = [
    ("(no flag)", "Create the environment if needed, then start the application."),
    ("--setup-only", "Build the environment but do not start the application."),
    ("--reinstall", "Rebuild the environment from scratch."),
    ("--check", "Report environment/tkinter/application-file status and exit."),
]

REPORT_SECTIONS = [
    ("Cover page", "Logo, title, customer, reference, operator, date, and a cover picture."),
    ("Contents", "The sections and their real page (slide) numbers; the PDF also gets bookmarks."),
    ("At a glance", "Right after the Contents: files, samples and spectra, format, instrument, "
     "operator, dates, counting time, the elements quantified and what else is in the report. "
     "A line is written only when the files record it."),
    ("Summary", "A short written overview of the experiment."),
    ("Quantification", "Atomic percent from CasaXPS fits, by sample and by depth level."),
    ("Figures", "One page (slide) per saved figure, drawn with its caption."),
    ("Camera pictures, SnapMaps and image maps", "Sample-view photos, mosaics, element-map pages and Kratos image maps."),
    ("Methods", "The automatically written methods paragraph."),
    ("Timing", "After Methods: first start, last finish, time in use, counting time and what was "
     "not counting (moves, settling, sputtering, dead time), plus the counting time of each sample."),
    ("Energy calibration", "The binding-energy calibration statement."),
    ("Acquisition metadata", "The tidied acquisition settings of every file."),
    ("Data files", "A checksummed list of the original files (the audit trail)."),
]

SHORTCUTS = [
    ("Space", "Tick or untick the selected row"),
    ("F2", "Rename the selected sample or region"),
    ("F11", "Focus mode — hide the side panels"),
    ("Ctrl+S", "Save the workbook"),
    ("▶ / ◀ →", "Play, or step, through the traces"),
    ("Page Up / Page Down", "Previous / next page of panels"),
    ("Home / End", "First / last page of panels"),
    ("Shift + mouse wheel", "Slide the trace window (long stacks)"),
    ("Esc", "Close the splash screen"),
]


def build_chapters(doc):
    # 1. Introduction --------------------------------------------------
    h1(doc, "1. Introduction")
    para(doc,
        f"{APP_NAME} is a desktop application for browsing, plotting and exporting "
        "X-ray Photoelectron Spectroscopy (XPS) data from a wide range of instruments "
        "and file formats. Open one or several files at once, tick the spectra you "
        "want to see, and they are plotted immediately — spectra of the same core "
        "level are stacked with a vertical offset on a shared panel, so they are easy "
        "to compare. Metadata, camera images and a stage map sit alongside the plot; "
        "spectra can be exported to CSV, VAMAS (ISO 14976) or NeXus, and a complete "
        "experiment can be turned into a PDF report, a PowerPoint deck, a Word "
        "document, a hand-over ZIP, or a self-contained offline HTML browser for a "
        "customer or collaborator. CasaXPS peak fits in your files are displayed, "
        "quantified and reported, never edited."
    )
    h2(doc, "Supported file formats")
    add_table(doc, FORMATS_HEADERS, FORMATS_ROWS, widths_cm=[4.0, 3.2, 9.4])
    para(doc,
        "Files are recognised by their content, not only by their file extension, so "
        "a renamed file still opens correctly. Every format that can be opened can "
        "also be exported to CSV, VAMAS or NeXus, which makes the application a converter "
        "between instrument formats (for example, Thermo .avg to VAMAS)."
    )
    para(doc,
        "Binding energy is calculated as photon energy minus kinetic energy "
        "(BE = hν − KE) whenever the photon energy is known, and is not "
        "charge-corrected until you apply a calibration (Chapter 11)."
    )

    # 2. Installation ----------------------------------------------------
    add_page_break(doc)
    h1(doc, "2. Installation and quick start")
    h2(doc, "Windows")
    bullets(doc, [
        "Install Python 3.8 or later from python.org and tick “Add python.exe "
        "to PATH” during setup.",
        "Double-click run.bat.",
    ])
    h2(doc, "macOS / Linux")
    para(doc, "In a terminal, in the application folder:")
    bullets(doc, ["chmod +x run.sh   (first time only)", "./run.sh"])
    para(doc,
        "On the first launch the application builds an isolated environment in "
        "./.venv and installs the required packages (an internet connection is "
        "needed once). Later launches start immediately, and nothing is installed "
        "into your system Python. The launcher re-installs automatically if its "
        "requirements change."
    )
    h2(doc, "Manual launch")
    para(doc, "For more control, run the launcher directly: python launch.py "
        "(python3 launch.py on macOS/Linux).")
    add_table(doc, ["Flag", "Effect"], LAUNCH_FLAGS, widths_cm=[3.5, 13.1])
    add_figure(doc, "The splash screen shown while the application starts.")

    # 3. Workspace window --------------------------------------------------
    add_page_break(doc)
    h1(doc, "3. The workspace window")
    para(doc,
        f"{APP_NAME} is a single window: a file tree on the left, a large plot in "
        "the middle, and an information column on the right (a Details panel above "
        "an Images / Stage map notebook). Drag any splitter to resize; sizes are "
        "remembered between sessions."
    )
    add_figure(doc, "The workspace window: file tree, plot area and information column.")
    h2(doc, "The ribbon")
    add_table(doc, ["Tab", "Contains"], [
        ("Home", "Open, folder, recent files, workbook, save, export (CSV, VAMAS, NeXus, "
         "regions and levels, metadata), save plot image."),
        ("Analyse", "Calibrate, identify peaks, ISS/REELS, sputter settings, instrument "
         "settings (NeXus), SnapMap, rename, notes."),
        ("Report", "Details, figures, Report generator, report PDF, slides, Word, hand-over "
         "ZIP, HTML browser, PDF previews."),
        ("View", "Theme, plot style, side panels, focus mode, expand/collapse, untick all."),
    ], widths_cm=[3.0, 13.6])
    para(doc,
        "Every ribbon button is a shortcut for a menu command — the menu bar "
        "still holds everything — and buttons that need spectra are dimmed "
        "until a file is open. Double-click a tab, or use the arrow at the right, "
        "to fold the ribbon down to just the tab row and give the plot the height "
        "back; the chosen tab and fold state are remembered. Beside About sit "
        "small launcher buttons for CasaXPS and KherveFitting (Chapter 4)."
    )
    add_figure(doc, "The tabbed ribbon: Home, Analyse, Report and View.")
    h2(doc, "Splash and About")
    para(doc,
        "A splash screen shows while the program starts; click it, or press Esc, "
        "to close it early. Help → About shows the version, a link to the "
        "project page, the libraries in use, and a Copy version info button for "
        "bug reports."
    )

    # 4. Opening files -----------------------------------------------------
    add_page_break(doc)
    h1(doc, "4. Opening and organising files")
    para(doc,
        "Use Open → Spectra files… to load several files of any "
        "supported format, or Open → Folder… to load every recognised "
        "file in a folder. Each file becomes a top-level node in the tree. A "
        "folder from a Thermo Avantage experiment, or its .VGX file, opens as one "
        "experiment instead (see Chapter 22)."
    )
    para(doc,
        "If a selection or folder holds the same dataset as both .avg and .vgd "
        "(Avantage), or as both .dset and .kal (Kratos Vision2 and its "
        "DumpDataset text), you are asked which to import (.avg and .dset are "
        "pre-selected). Tick “Remember my choice” to stop being asked about "
        "that pair of formats; File → “Ask about .avg / .vgd and .kal / .dset "
        "duplicates again” brings the question back. A folder’s own "
        "index-only .dset, which holds no spectra, is skipped."
    )
    para(doc,
        "Every node that holds spectra has a tick box — click it, or press "
        "Space. Ticking a sample, region folder or whole file ticks everything "
        "beneath it; a partly-ticked parent shows a bar. Filter narrows the tree "
        "without losing your ticks. Right-click a row to tick or untick a whole "
        "subtree, export from there down, or remove a file. On a single region, "
        "“Tick every … region (all samples)” and “Untick every … region (all "
        "samples)” act on every region of that name in every loaded file — "
        "tick all the C 1s, then untick the odd ones out, to build a report "
        "figure. CasaXPS and KherveFitting have a small icon button beside "
        "About. If the program is not found automatically, the first click asks "
        "you to show where it is and remembers the answer; right-click a "
        "button to point at another copy or hide it (Tools → Open / Locate / "
        "Show the … button has the same)."
    )
    add_figure(doc, "The file tree with several spectra ticked and their colour swatches.")

    # 5. Plotting spectra ----------------------------------------------------
    add_page_break(doc)
    h1(doc, "5. Plotting spectra")
    para(doc,
        "Ticked spectra are plotted at once, and the tree is the legend. Spectra "
        "sharing an element name (every C 1s, across samples and files) are drawn "
        "on one panel, stacked with a vertical offset; other elements get their "
        "own panels. A ticked box in the tree is a swatch in the trace's colour: "
        "one colour per file when several files are loaded, otherwise one per "
        "sample, and a fading ramp of one hue for long stacks such as depth "
        "profiles. Stacked panels have no y-axis ticks — a scale bar gives "
        "the intensity scale, and each trace is labelled at its right-hand end. "
        "The selected spectrum is drawn heavier than the rest."
    )
    h2(doc, "View controls")
    add_table(doc, ["Control", "What it does"], [
        ("Group by", "Element name; Energy range (spectra whose ranges overlap by at "
         "least half share a panel); or Element, per sample / per file."),
        ("Normalise", "None; Max = 1; Area = 1; or At cursor — click a panel to set "
         "an energy, and every spectrum in it is scaled to match there."),
        ("Offset", "The gap between stacked traces (0 overlays them). Reverse stack "
         "flips the order."),
        ("View", "Stack (the default); Waterfall 3D (a rotatable 3-D plot); "
         "Heatmap (intensity as colour, with a colour bar); or Fit (one trace "
         "with its CasaXPS fit forced on, Chapter 20)."),
        ("Z axis", "What the trace axis shows in a waterfall or heatmap: Auto (etch "
         "time, else etch level, else acquisition time, else trace order), or pick one."),
        ("Colour", "Theme default, or a named scale (Viridis, Plasma, Magma, …) "
         "applied to the heatmap and spread across a stack's traces; Reverse flips it. "
         "Black (single colour) draws every trace in one colour (black; the theme's "
         "text colour on a dark plot) — pair it with the Data points preset for "
         "black points."),
        ("Axes", "Colour of the axis lines, ticks and labels: Theme default, Black, "
         "White, or a colour you choose."),
        ("Energy", "Binding or Kinetic (KE = hν − BE, when the photon energy "
         "is known); KE top axis mirrors binding energy along the top as kinetic energy."),
    ], widths_cm=[3.0, 13.6])
    h2(doc, "Different views on one page")
    para(doc,
        "The view row sets the default for every panel, but any panel can "
        "differ: right-click it and choose View, Normalise, Offset, Z axis, "
        "Fit layers or Nearby lines for that panel alone, so one page can hold "
        "a waterfall, a stack and a fitted spectrum. Identify peaks… is on the "
        "same menu, “Use the page’s view” takes a panel back to the default, and "
        "View → Reset panel views clears every override. A panel is identified "
        "by its group label, so use “Element, per sample” grouping to give two "
        "samples’ C 1s different views. Panel views are saved in the workbook "
        "and in each saved figure, so reports show them as you set them."
    )
    h2(doc, "Zooming, and saving what you see as a figure")
    para(doc,
        "The magnifier and hand buttons under the plot zoom and pan; the tool "
        "stays switched on after a zoom until you press its button again. "
        "With it on, a drag still zooms or pans, but a plain click now works "
        "as usual: right-click opens the panel menu (so Identify peaks… and "
        "Nearby lines can be used on the zoomed view) and, with Identify "
        "open, a left click adds the element line at the clicked energy."
    )
    para(doc,
        "To keep what you are looking at, right-click the plot and choose "
        "“Save this view as a figure…” (right-click outside the panels, or "
        "use Workbook → “Save current view as a figure…”, if you prefer the "
        "menu). Give it a name and it appears in Workbook → Figures…, where "
        "you can add a caption. A figure remembers the zoom of each panel you "
        "had zoomed, so the report, the slides, the Word document and the "
        "hand-over images show that energy range; panels you did not zoom "
        "keep their full range, and a figure saved before this existed keeps "
        "whatever zoom is on screen when you recall it."
    )
    add_figure(doc, "A stack view: several spectra of one core level, offset vertically.",
              image_path=os.path.join(FIGDIR, "fig_stack.png"))
    add_figure(doc, "A Waterfall 3D view of a depth profile.",
              image_path=os.path.join(FIGDIR, "fig_waterfall.png"))
    add_figure(doc, "A Heatmap view of a depth profile, with its colour bar.",
              image_path=os.path.join(FIGDIR, "fig_heatmap.png"))

    # 6. Paging ---------------------------------------------------------
    add_page_break(doc)
    h1(doc, "6. Paging, scrolling and playback")
    para(doc,
        "Panels per page chooses how many panels are shown at once (Auto, 1, 2, 4, "
        "6, 9, 12 or 16); scroll between pages with the mouse wheel, the scrollbar "
        "beside the plot, Page Up / Page Down, Home / End, or the Prev / Next "
        "buttons."
    )
    para(doc,
        "Traces per panel is either All or a fixed number. For a long stack (say a "
        "200-level depth profile) each panel then shows a window of that many "
        "traces; slide the window with Shift + mouse wheel or the Traces slider "
        "under the plot."
    )
    para(doc,
        "The ▶ Play button, or the ◀ / → keys, step through the "
        "traces in view — set Traces to 1 to step through a depth profile one "
        "level at a time."
    )

    # 7. Selecting --------------------------------------------------------
    add_page_break(doc)
    h1(doc, "7. Selecting a spectrum: Details, Images, Stage map and Quantification")
    para(doc,
        "Ticking a row plots it; selecting a row (rather than ticking it) fills "
        "the Details panel with the sample, acquisition and region information "
        "(all of it copyable), and the Images / Stage map tabs, which only appear "
        "when the loaded files carry images or stage positions."
    )
    add_figure(doc, "The Details panel for a selected spectrum.")
    h2(doc, "Quantification tab")
    para(doc,
        "When a ticked region carries a CasaXPS fit, a Quantification tab joins "
        "the Images and Stage map tabs. It gives atomic percent from the fit "
        "areas divided by sensitivity factors (RSF), for the samples you have "
        "ticked, using the same code as the PDF, the slides and the HTML page, "
        "so the numbers agree everywhere. Nothing is guessed: a region with no "
        "RSF or no area is left out and the tab says why."
    )
    bullets(doc, [
        "Sample chooses which sample to show. A survey and the ticked "
        "high-resolution regions are never one total: each sample’s survey "
        "fits appear as their own “<sample> (survey)” entry.",
        "Each fitted region has a tick box. A region fitted in more than one "
        "spectrum is counted once by default (the dedicated scan, not the "
        "survey), and an element with a known standard line (Pt 4f rather than "
        "Pt 4d) counts that line. Tick or untick any region to decide for "
        "yourself; Reset ticks returns to the automatic choice. Your ticks are "
        "saved in the workbook and followed by the reports and the HTML page.",
        "RSF chooses the sensitivity-factor fallback for a region whose file "
        "records none (off by default): the file’s own factor is always used "
        "first, then the factors of its components, and only then a reference "
        "table (Scofield, Kratos Axis F 1s, or Scofield with a TPP-2M or KE^0.6 "
        "mean-free-path correction). A substituted value is always labelled as "
        "such, never shown as though the file had recorded it.",
        "Show picks a depth level; a sample with two or more levels opens on a "
        "depth profile (by element, by chemical state, or state share).",
        "Divide out the transmission function applies the file’s transmission "
        "(only offered when the file has one; off by default).",
        "Use CasaXPS’s own numbers (on by default, available when CasaXPS’s "
        "own quantification export, Quant_regions.txt / Quant_survey.txt, was "
        "found beside the data) takes the percentages from that export instead "
        "of recomputing, renormalised over the regions that count. A region the CasaXPS file has no row for is left out with a "
        "note rather than filled with a different calculation. Untick the box to "
        "recompute everything.",
        "Export CSV… writes the table with your ticks applied (UTF-8 with a "
        "BOM, so Excel shows α and µ correctly). The neighbouring CasaXPS "
        "quant tab, shown when such export files were found, lists them "
        "exactly as CasaXPS wrote them.",
    ])
    add_figure(doc, "The Quantification tab: regions with tick boxes, RSF and the "
              "recomputed or CasaXPS atomic percent.")
    para(doc,
        "Selecting several rows at once (or a whole sample or file) tidies "
        "Details: a setting that is the same for all of them, such as photon "
        "energy or lens mode, is stated once; settings that differ are grouped by "
        "value. The metadata PDF (Chapter 14) does the same for each sample."
    )
    h2(doc, "Holder photo calibration")
    para(doc,
        "Overlaying analysis positions on a photo needs a one-time Calibrate… "
        "step. The calibration panel works live: tick Flip X / Flip Y, nudge the "
        "markers with the arrow keys, rotate or spread them, or type exact values "
        "(image centre in millimetres, millimetres per pixel, rotation) and watch "
        "the markers move onto the samples. The calibration is saved in the "
        "workbook, and the last one used seeds new workbooks. Markers carry a "
        "halo so their names stay readable over any photo; click a marker, on the "
        "photo or on the Stage map, to select that sample in the tree."
    )
    add_figure(doc, "The calibration panel, with markers placed on the sample photo.")

    # 8. Themes / layout ---------------------------------------------------
    add_page_break(doc)
    h1(doc, "8. Colour themes and layout")
    para(doc,
        "Six colour themes are built in: Light (the default), Dark (the plot sits "
        "recessed below the chrome, like an instrument screen), Midnight, "
        "Solarized Light, High contrast, and System (the native operating-system "
        "look). Change the theme from the Theme box or View → Colour theme; "
        "your choice is remembered. Every theme has its own colour-blind-safe "
        "data palette and meets WCAG AA text contrast. PDFs always print on white."
    )
    para(doc,
        "The Files and Details buttons in the toolbar show or hide the side "
        "panels, and Focus (F11) hides both so the plot fills the window. Hover "
        "any control for a short explanation."
    )
    add_figure(doc, "The same experiment shown in the Light and Dark themes.",
              image_path=os.path.join(FIGDIR, "fig_theme_compare.png"))

    # 9. PDF preview -------------------------------------------------------
    add_page_break(doc)
    h1(doc, "9. PDF preview and saving plot images")
    para(doc,
        "Preview spectra and Preview metadata show the PDF inside the "
        "application, with page navigation, zoom, Save as…, and Open in "
        "viewer. The spectra preview lets you change panels per page, portrait "
        "or landscape orientation, and whether to use only the traces currently "
        "in view; Save as… writes exactly what you see. Without PyMuPDF "
        "installed, the PDF opens in your default viewer instead."
    )
    para(doc,
        "Save plot image… writes the current view as PNG, SVG or PDF, at "
        "any size and resolution."
    )

    # 10. Exporting --------------------------------------------------------
    add_page_break(doc)
    h1(doc, "10. Exporting spectra")
    para(doc,
        "Export → Ticked spectra to CSV / VAMAS / NeXus writes exactly what is "
        "currently ticked. Export → Regions and levels… opens a dialog "
        "(pre-set to your ticks) for picking individual regions or depth-profile "
        "levels. VAMAS output is CasaXPS-compatible: a kinetic-energy abscissa "
        "with Intensity and the spectrometer's Transmission function as a "
        "corresponding variable (toggle it off in the dialog if you do not want "
        "it)."
    )
    para(doc,
        "Export → Metadata to CSV / PDF saves the per-sample acquisition "
        "metadata; with several files open, select a row belonging to the file "
        "you want first."
    )
    h2(doc, "NeXus (.nxs)")
    para(doc,
        "Export → Ticked spectra to NeXus… (also in the File menu, the tree’s "
        "“Export from here down”, the Export dialog and the hand-over ZIP) "
        "writes an NXxps file, which needs the optional h5py library. There is "
        "one entry per spectrum, holding the instrument and source settings, the "
        "energy axis, the binding-energy correction, the transmission function "
        "and any CasaXPS fit (peaks, background, envelope, residual and reduced "
        "chi-square), plus the full metadata as a note. Fields the instrument "
        "file never recorded are left out, never invented."
    )
    para(doc,
        "Tools → Instrument settings (NeXus)… (Analyse ▸ Instrument) lets you "
        "state, once per file, what instrument files rarely record: X-ray "
        "source type, energy-dispersion and collection-column schemes, detector "
        "and amplifier type, analyser scan mode, work function, energy "
        "resolution, operator and affiliation, and the UTC offset of the "
        "recorded times. What you enter wins over what the file says, is kept "
        "in the workbook, and lets the .nxs pass strict NXxps validation; a "
        "field you leave unset is simply left out."
    )
    add_figure(doc, "The Instrument settings (NeXus) dialog.")

    # 11. Editing / calibration ---------------------------------------------
    add_page_break(doc)
    h1(doc, "11. Editing, calibration and element labels")
    para(doc,
        "Nothing in this chapter changes the instrument files: your edits are "
        "stored beside the data, in the workbook, and applied when you plot, "
        "export or build a report."
    )
    h2(doc, "Rename and notes")
    para(doc,
        "Press F2, or right-click a sample or region, to give it a display name; "
        "the original name is always kept and shown in Details. Notes… adds "
        "free text to a sample or region."
    )
    h2(doc, "Edit metadata")
    para(doc,
        "Double-click a value in Details (or right-click it for Edit value, Add "
        "field, or Reset) to change it. Edited values carry a pencil mark and "
        "flow into the PDF, PowerPoint and CSV exports."
    )
    h2(doc, "Calibrate binding energy")
    para(doc,
        "Tools → Calibrate binding energy…: pick a reference spectrum, "
        "find the peak (or click it on the plot), choose the reference (C 1s "
        "284.8 eV, Au 4f7/2 83.95 eV, Ag, Cu, a Fermi edge, or your own value), "
        "and apply the shift to a region, a sample, or a whole file. Plots, CSV "
        "and VAMAS exports use the shifted energies (VAMAS carries the shift "
        "through the source energy, so kinetic energies are unchanged), and the "
        "report gets a calibration statement automatically. A charge "
        "correction already stored by CasaXPS in a VAMAS file is applied for "
        "you and shown in Details as “BE calibration (CasaXPS)”; a shift you "
        "set yourself takes precedence over it."
    )
    h2(doc, "Identify peaks")
    para(doc,
        "Tools → Identify peaks… (or right-click a spectrum → Identify peaks…): "
        "click a survey peak to list candidate "
        "element lines, add the one you want as a marker, or use Auto-label to "
        "label every peak at once. Markers follow binding-energy calibrations and "
        "the kinetic-energy axis. Line positions are approximate typical values "
        "— chemical shifts of a few eV are normal, so the default search "
        "window is ±3 eV."
    )
    para(doc,
        "A spin-orbit doublet is named once by default: a peak near 454 eV "
        "offers “Ti 2p”, and one near 84 eV “Au 4f”, whichever component you "
        "click. Tick “Show spin-orbit components (2p3/2, 2p1/2)” in the dialog "
        "(the interactive HTML page has the same box) to name the components "
        "separately; the choice is remembered, and Auto-label follows it. "
        "Markers you already placed keep the name they were given. Only lines "
        "the photon energy can reach are offered, so a Mg Kα source does not "
        "list a level at 1300 eV, while deeper levels appear for Ag Lα and "
        "harder sources. The line table is Thermo Avantage’s own library, "
        "extended with lanthanide and actinide levels, deep levels and a few "
        "elements it lacks, taken from the X-ray Data Booklet table that ships "
        "with KherveFitting."
    )
    para(doc,
        "Beneath the element lines the dialog also lists chemical states: "
        "literature binding energies for a core level (for example an iron "
        "oxide’s Fe 2p3/2 peaks), each with its source shown when you select "
        "it. They are suggestions for you to confirm and are never used by "
        "Auto-label. A link opens the free NIST XPS Database for anything "
        "beyond these curated tables. On a survey that came from CasaXPS, "
        "“Label from CasaXPS regions” labels the peaks directly from the "
        "regions named in the file, for every ticked survey, instead of from "
        "the approximate line table."
    )
    add_figure(doc, "The Identify peaks dialog, with candidate element lines listed.")
    h2(doc, "Cursor read-out and other comforts")
    para(doc,
        "The status bar always shows the binding energy, kinetic energy and "
        "intensity under the pointer. Other comforts: File → Open recent, "
        "drag files or folders onto the window, a progress box with Cancel when "
        "loading many files, and the play/step controls from Chapter 6."
    )

    # 12. Workbooks --------------------------------------------------------
    add_page_break(doc)
    h1(doc, "12. Experiment workbooks (.xpscontainer)")
    para(doc,
        "The Workbook menu saves everything about an experiment in one file "
        "that you can reopen at any time (or double-click, or pass on the "
        "command line). A workbook holds:"
    )
    bullets(doc, [
        "The original data files, byte-for-byte, with SHA-256 hashes as "
        "provenance; files are re-read on opening, so reader improvements apply "
        "to old workbooks.",
        "The look: what is ticked, the view, grouping, normalisation, energy "
        "scale, colour scale, axis colour, panels/traces and any “At "
        "cursor” energies.",
        "Details and notes — title, customer, reference, operator, date, a "
        "free-text summary and a letterhead logo.",
        "Figures — any number of named looks with captions.",
        "A snapshot of the acquisition metadata and a preview image.",
        "Your annotations: display names, notes, metadata edits, energy "
        "shifts, peak markers, sputter and instrument settings, and the "
        "ticks you made in the Quantification tab.",
        "The Report generator’s choice (sections, order, options, cover), "
        "and any CasaXPS CSV export you imported (stored verbatim and "
        "matched to the fits again on opening).",
        "Optionally, the parsed results (Workbook → “Store the parsed "
        "results in the workbook”, on by default). They are advisory only: "
        "opening always re-reads the original files. Their one use is "
        "Workbook → “Data browser from a saved workbook…”, which writes the "
        "HTML browser without loading any instrument file (saved figures, "
        "holder photo, camera pictures and SnapMaps are not in that page).",
    ])
    para(doc,
        "Save with Ctrl+S; the title bar shows an asterisk for unsaved changes, "
        "and closing the application asks whether to save. The file is a ZIP "
        "archive of JSON and the original files, so it can be inspected with "
        "any zip tool and never runs code."
    )
    add_figure(doc, "The Workbook Details dialog.")
    para(doc,
        "Metadata layout: settings that are the same for every region (photon "
        "energy, lens mode, …) are stated once at the top, settings constant "
        "within a sample sit on that sample's line, and the rest is a compact "
        "scan table. A depth profile collapses to one row (e.g. “levels "
        "0–60, etch 0–1800 s, 30 s steps”) only where that "
        "reproduces every level exactly; otherwise a per-level table is used."
    )

    # 13. Report generator ---------------------------------------------------
    add_page_break(doc)
    h1(doc, "13. The Report generator")
    para(doc,
        "Workbook → Report generator… (or Report ▸ Generator on "
        "the ribbon) is where you say what a report contains and in what "
        "order. The same choice is used for the PDF report, the PowerPoint "
        "deck, the previews and the hand-over package; it is remembered and "
        "saved with the workbook."
    )
    add_table(doc, ["Section", "Contents"], REPORT_SECTIONS, widths_cm=[4.2, 12.4])
    h2(doc, "The cover")
    para(doc,
        "The Cover tab offers five designs drawn from one accent colour "
        "(spectrum ribbon, band, minimal, your own data, peak map), a picture "
        "of your own (or one dropped into assets/covers/), or no picture, in "
        "one of six accent colours or a colour you choose, and the font of the "
        "PDF's text (slides and Word keep Calibri). Presets never change "
        "the cover."
    )
    para(doc,
        "In the PDF the cover is a full page: the design (or your picture, "
        "cropped from its middle, never stretched) fills the A4 or Letter page "
        "and the title, customer, reference, operator, date and letterhead sit "
        "on a clear panel whose position — top, middle or bottom — you choose "
        "under “Text position”. The text shrinks to fit, so the cover is "
        "always one page, with no footer. “No picture” gives a text-only cover. "
        "The slides and the Word document use a banner strip of the same design "
        "instead."
    )
    h2(doc, "Options")
    para(doc,
        "The Options tab holds three choices that apply to every output: "
        "whether the data-files list carries a checksum column, whether a divider "
        "page or slide precedes each long section (five or more pages), and "
        "whether overlapping camera pictures are also stitched into a mosaic."
    )
    h2(doc, "Presets")
    para(doc,
        "Built-in presets (Everything, Customer report, Quick look, Audit "
        "trail) and your own saved presets fill in the ticks in one go. "
        "Sections with many items (figures, pictures, files, samples) open "
        "with a double-click, and All / None ticks every item of the selected "
        "section. A report saved before At a glance or Timing existed keeps "
        "them switched off, so an old report does not grow pages."
    )
    para(doc,
        "If you changed which regions count in the Quantification tab, the "
        "dialog says how many differ from the automatic choice, with a Reset "
        "button. Your choice reaches the PDF, the slides, the Word document and "
        "the HTML browser; it is saved with the workbook, not in a preset."
    )
    add_figure(doc, "The Report generator dialog: sections, order and options.")
    add_figure(doc, "A cover design as drawn across the PDF's full page (the text "
              "panel is laid over the clear part, at the position you choose).",
              image_path=os.path.join(FIGDIR, "fig_cover.png"), width_cm=9.0)

    # 14. PDF report and deck -------------------------------------------------
    add_page_break(doc)
    h1(doc, "14. The PDF report, PowerPoint deck and Word document")
    para(doc,
        "Workbook → Experiment report — save PDF…, Export PowerPoint… and "
        "Export Word document… (also on the Report ribbon) build the same "
        "sections in the same order from the one Report generator choice. The "
        "Word document is fully editable. Contents lists every section with "
        "its real page (or slide) number, and its entries in the PDF are "
        "clickable; the PDF also gets bookmarks. The PDF and the slides get a "
        "divider page or slide before a long section, the PDF marks its audit "
        "sections (metadata, files) with a small “Appendix” label, and every "
        "slide is numbered “n of N”."
    )
    h2(doc, "At a glance and Timing")
    para(doc,
        "At a glance is a quiet block of single-line facts after the Contents: "
        "how many files, samples and spectra, the format, instrument and "
        "operator, when it was acquired, the counting time, the elements "
        "quantified and what else the report holds. Timing, after Methods, "
        "separates the time the instrument was counting from the time it was "
        "in use (moves, settling, sputtering, dead time). A line is written "
        "only when the files record it: a Kratos file stores when a run started "
        "but not when it ended, so its Timing section shows first and last "
        "start and the counting time, with a note saying why."
    )
    h2(doc, "Quantification")
    para(doc,
        "Atomic percent comes from CasaXPS peak-fit areas and sensitivity "
        "factors: one table per sample (with chemical states), or, for a depth "
        "profile, a chart and a table by level. A region fitted in more than "
        "one spectrum at a level is counted once — the dedicated scan, not "
        "the survey — and this is stated on the page. An element counted "
        "from two different lines is flagged. No transmission correction is "
        "applied in reports. Each sample can be ticked separately in the "
        "Report generator."
    )
    para(doc,
        "A survey and the high-resolution regions are never added into one "
        "total: a sample’s survey gets its own “<sample> (survey)” table. "
        "Where CasaXPS’s own quantification files name the sample, the tables "
        "show a CasaXPS %At column and use those percentages; a region "
        "the CasaXPS file has no row for is left out with a note, and a sample "
        "the files do not name is recomputed and says so. A fitted sample also "
        "shows CasaXPS’s D-parameter rows where they exist. Table columns that "
        "are empty for every row (a survey has no fit RMS or chi-square) are "
        "dropped, and a fit legend that names two components alike adds where "
        "each peaks, for example “Pt 4f (73.3)” and “Pt 4f (76.6)”. Regions you "
        "ticked or unticked in the Quantification tab are followed, and the "
        "page says so."
    )
    h2(doc, "Camera pictures, SnapMaps and mosaics")
    para(doc,
        "When the loaded files include camera images (an Avantage experiment), "
        "overlapping pictures can also be stitched into one large mosaic; a "
        "note on the page says how many overlaps were matched. Camera pictures "
        "appear six to a report page (three to a slide), each with the analysis "
        "points that fall in it and a scale bar; one page or slide is added per "
        "SnapMap site, showing the camera picture beside a grid of element maps."
    )
    h2(doc, "Methods text")
    para(doc,
        "Workbook → Details… has a Methods box holding a paragraph "
        "written automatically from what your files record: instrument and "
        "source, pass energies, step sizes, dwell times, lens mode, "
        "neutraliser, sputtering, depth profiles, dates and the calibration "
        "statement. A setting a file does not record is left out, never "
        "guessed. Edit the text to use your own wording; Regenerate brings the "
        "automatic text back."
    )
    add_figure(doc, "A sample page from the PDF report (the acquisition "
              "metadata and data-files appendix pages).",
              image_path=os.path.join(FIGDIR, "fig_report_page.png"))
    add_figure(doc, "A sample quantification table.",
              image_path=os.path.join(FIGDIR, "fig_quant_table.png"))

    # 15. Hand-over ----------------------------------------------------------
    add_page_break(doc)
    h1(doc, "15. Hand-over package (ZIP)")
    para(doc,
        "Workbook → Hand-over package (ZIP)… puts a whole experiment "
        "into one ZIP file for a customer or collaborator. It contains the "
        "report PDF, the methods text, one VAMAS and one CSV file per sample "
        "(with your display names and energy shifts applied), the metadata as "
        "CSV, a NeXus file per sample when h5py is installed, every "
        "saved figure as a PNG, optionally the interactive data "
        "browser and the workbook itself, a README.txt listing everything "
        "included, and SHA256SUMS.txt (checked with sha256sum -c "
        "SHA256SUMS.txt). Tick what you want to include in the dialog."
    )

    # 16. HTML browser ---------------------------------------------------------
    add_page_break(doc)
    h1(doc, "16. Interactive HTML data browser")
    para(doc,
        "Workbook → Interactive data browser (HTML)… writes one "
        "self-contained .html file that anyone can open in a modern browser, "
        "offline, with nothing to install. It lets the reader filter the "
        "sample list, tick spectra to plot them (stacked or overlaid, "
        "normalised, binding or kinetic energy, drag to zoom, hover for "
        "values), step through depth levels one at a time, read the "
        "acquisition metadata, notes and methods, look at your saved figures "
        "with their captions, see the holder photo with the analysis "
        "positions, and download spectra as CSV. It has light, dark and print "
        "styles, and makes no network requests."
    )
    para(doc,
        "For an Avantage experiment it also holds a Camera images tab (each "
        "picture with its analysis points and a scale bar) and a SnapMaps tab "
        "(the same viewer as in the application: drag the energy window, drag "
        "a region for its spectrum, switch element, choose a colour scale, "
        "overlay on the camera image, and download the map or spectra as CSV)."
    )
    para(doc,
        "Quantification and Depth profile tabs mirror the application’s "
        "(the same numbers, including the RSF fallback choice, the preferred-"
        "line default and CasaXPS’s own percentages); the page starts from "
        "the regions you ticked or unticked in the Quantification tab, and the "
        "reader can change them. Fits are drawn on single-spectrum panels "
        "(components, envelope, background and a residual band) with a "
        "per-component table. When you imported a CasaXPS CSV export "
        "(Chapter 20), a “CasaXPS exported curves” box, ticked by default, "
        "switches the plot, tables, quantification and CSVs between CasaXPS’s "
        "own curves and the reconstruction. An Identify peaks mode lists the "
        "element lines near a clicked peak, and survey peaks can be labelled "
        "automatically (off by default, since the line table is approximate). "
        "Zoom stays within the data, every panel has a PNG button, and "
        "Download everything saves one ZIP with the CSVs, quantification, "
        "methods and a README."
    )
    para(doc,
        "Workbook → Data browser from a saved workbook… writes the same page "
        "from a saved workbook without reading any instrument file."
    )
    para(doc,
        "A working example, built from two synthetic samples, is included "
        "alongside this manual as demo_browser.html — open it in any "
        "browser to see the real page before adding your own screenshot below."
    )
    add_figure(doc, "The interactive HTML data browser, opened in a web browser.")

    # 17. Plot style -----------------------------------------------------------
    add_page_break(doc)
    h1(doc, "17. Plot style")
    para(doc,
        "View → Plot style… (or the Style… button under the plot "
        "controls) opens one dialog for how plots look: font (IBM Plex Sans, Source "
        "Sans 3, Inter, IBM Plex Serif, STIX Two Text and IBM Plex Mono are "
        "bundled; any installed font also works) and sizes, line "
        "width and style, markers, fill under traces, frame, tick direction "
        "and length, grid, panel titles and axis labels, y units, energy and "
        "intensity ranges, trace labels, and the size and resolution of saved "
        "images."
    )
    para(doc,
        "Changes apply at once and reach the screen, PDFs, slides and Save "
        "plot image…. Pick a preset (Journal – compact, Presentation "
        "– large, Data points, Filled peaks, …) or save your own. The "
        "current style is remembered between sessions, saved in the workbook, "
        "and stored with each saved figure, so a figure keeps its own look in "
        "the report even after you change the live plot."
    )
    add_figure(doc, "The Plot style dialog.")

    # 18. Sputter -----------------------------------------------------------
    add_page_break(doc)
    h1(doc, "18. Sputter settings, depth and fluence")
    para(doc,
        "Tools → Sputter settings… holds the ion-gun settings of each "
        "depth profile: ion and charge state, energy, current, raster size and "
        "etch rate. These are prefilled wherever the file states them; nothing "
        "is guessed, so a bare number whose unit is unknown is left for you to "
        "fill in."
    )
    para(doc,
        "With these settings recorded, the Z axis of a waterfall or heatmap "
        "can show Depth (nm) (etch rate × etch time) or Fluence "
        "(ions/cm², from current, time, charge and raster area). Asking "
        "for a value that cannot be worked out tells you exactly what to enter "
        "and where. The settings are kept per sample in the workbook and appear "
        "in the metadata and the methods text."
    )

    # 19. VAMAS metadata --------------------------------------------------------
    add_page_break(doc)
    h1(doc, "19. VAMAS that keeps its metadata")
    para(doc,
        "VAMAS has no fields for most acquisition details, so a file exported "
        "from this application carries them in its comments instead: lens "
        "mode, aperture, neutraliser, ion gun, dates, stage position, depth "
        "level and etch time, sputter settings, your notes and any energy "
        "shift. Other software simply shows this as plain text. Reading such a "
        "file back into the application restores all of it, while values VAMAS "
        "stores exactly (photon energy, pass energy, dwell, step) are never "
        "taken from the text. Files without this information read exactly as "
        "before."
    )

    # 20. CasaXPS fits --------------------------------------------------------
    add_page_break(doc)
    h1(doc, "20. CasaXPS fits")
    para(doc,
        "A VAMAS file saved from CasaXPS after peak fitting carries the fit in "
        "its comments. Opening such a file shows the fit under any panel that "
        "holds one spectrum: tick Components, Envelope and/or Background in "
        "the Fit row under the plot controls. A depth profile keeps one fit "
        "per level."
    )
    para(doc,
        "CasaXPS's own binding-energy charge correction is carried over "
        "automatically and appears in Details (“BE calibration "
        "(CasaXPS)”) and in the report's calibration statement."
    )
    para(doc,
        "GL and SGL peak shapes, and Shirley, linear and the two-parameter "
        "(U 2) Tougaard backgrounds, are computed exactly. The St Offset and "
        "End Offset of a CasaXPS region are applied to the background. Other "
        "shapes are reconstructions: LA and LF, Doniach-Sunjic (DS), the "
        "asymmetric Gelius shapes A(a,b,n)GL / SGL and TLA, and the other "
        "Tougaard cross sections (U Poly, U Si, U SiO2, U Ge, U Al, U 4, plain "
        "and W Tougaard). The ones checked against real CasaXPS fits agree to "
        "within a few percent of peak height; where a shape cannot be "
        "reproduced (CasaXPS’s H, F and QF shapes, E Tougaard, Spline "
        "backgrounds), the components are drawn without an envelope and the "
        "status bar says so. The fit itself is read-only — fit your data in "
        "CasaXPS, then review it here. The fit table also gives each region’s "
        "residual and Poisson-weighted reduced chi-square."
    )
    h2(doc, "Importing a CasaXPS CSV export")
    para(doc,
        "To see exactly what CasaXPS drew, rather than a reconstruction, use "
        "Tools → Import CasaXPS CSV export… on a CasaXPS “Export All to ASCII” "
        "file (either layout). Each exported spectrum is matched to a region "
        "that already carries a CasaXPS fit, by comparing the data itself, "
        "and its components are lined up by binding-energy position; a "
        "region that cannot be matched cleanly is reported and skipped rather "
        "than guessed. The CasaXPS curves are then available through the "
        "“Use CasaXPS CSV curves” checkbox beside the fit toggles (off until a match "
        "exists), and flow into the fit table, areas and CSV exports. The "
        "imported file is stored inside the workbook and matched again when "
        "you reopen it."
    )
    h2(doc, "KherveFitting projects and peak libraries")
    para(doc,
        "A KherveFitting .kfit project opens like any other file and shows its "
        "fits, backgrounds and (when its results table has them) sensitivity "
        "factors through the same fit toggles and Quantification tab. Tools → "
        "Import KherveFitting peak model… opens a standalone Peaks Library "
        ".json as a fit-only reference: there is no measured spectrum, so the "
        "region shows the model’s own curve and says so. Note that KherveFitting "
        "may already have applied a charge correction to the stored energies; "
        "it is shown as metadata and never applied twice."
    )
    add_figure(doc, "A fitted spectrum with its components, envelope and background shown.",
              image_path=os.path.join(FIGDIR, "fig_casafit.png"))

    # 21. ISS/REELS -------------------------------------------------------------
    add_page_break(doc)
    h1(doc, "21. ISS and REELS")
    para(doc,
        "Tools → ISS / REELS… works on the one spectrum you have "
        "ticked, on whatever energy axis it uses."
    )
    h2(doc, "ISS peaks")
    para(doc,
        "Give the ion (H⁺, He⁺, Ne⁺, Ar⁺), the beam energy "
        "(read from the file where it is recorded) and the scattering angle "
        "for your instrument. Click a peak on the plot and the elements that "
        "could scatter the ion to that energy are listed, nearest first, from "
        "the single-collision scattering model. Add marker labels the peak, or "
        "type the elements you expect and Mark places each at its predicted "
        "energy. ISS markers sit at kinetic energy, so a binding-energy "
        "calibration never moves them."
    )
    add_figure(doc, "An ISS spectrum with candidate elements marked at their "
              "predicted scattered-ion energies.",
              image_path=os.path.join(FIGDIR, "fig_iss.png"))
    h2(doc, "REELS band gap")
    para(doc,
        "Find the elastic peak (automatically, by typing it, or by clicking "
        "it), then click two points on the rising edge of the loss spectrum. "
        "The straight line through them meets the baseline at the band gap, "
        "which is drawn on the plot and stored in the workbook and the "
        "spectrum's metadata. Points that do not give a positive gap are "
        "explained rather than stored as a result."
    )
    add_figure(doc, "The REELS band-gap construction: elastic peak, tangent and baseline.",
              image_path=os.path.join(FIGDIR, "fig_reels.png"))

    # 22. Avantage / SnapMap -----------------------------------------------------
    add_page_break(doc)
    h1(doc, "22. Avantage experiments, camera images and SnapMaps")
    para(doc,
        "Thermo Avantage writes one .VGD file per scan into a folder tree "
        "beside its .VGX file. Open → Folder… on that folder (or on "
        "the .VGX, or on a single sample folder inside it) loads everything as "
        "one experiment, with a progress box you can cancel. The tree runs "
        "experiment → sample → analysis point → scan, in the "
        "order the .VGX file says they were run."
    )
    para(doc,
        "Camera images: the sample-view pictures Avantage takes at each point "
        "carry their own stage calibration, so no manual calibration is "
        "needed. Select a point and its picture appears in the Images tab, "
        "with the analysis points that fall inside it, the outline of any "
        "SnapMap taken there, and a scale bar. Click a point in the picture to "
        "select it in the tree."
    )
    para(doc,
        "SnapMaps (a spectrum at every pixel) appear as one region each, "
        "marked (SnapMap). Double-click one to open the viewer: drag across "
        "the spectrum to choose the energy window (Remove background takes a "
        "sloping baseline off first), drag a box or click a pixel on the map "
        "to see that area's spectrum, lay the map over the camera picture, and "
        "save the picture, the map values, or the spectra. A Smoothing choice "
        "(None, Savitzky-Golay, Fourier low-pass or Gauss-Hermite Smooth) with "
        "a strength control cleans noisy map spectra for display; the Fourier "
        "methods remove the straight line from first to last point before "
        "filtering, so a sloping spectrum does not ring at its ends."
    )
    add_figure(doc, "The SnapMap viewer: the element map and the selected area's spectrum.")

    # 23. Depth profiles -------------------------------------------------------
    add_page_break(doc)
    h1(doc, "23. Depth profiles")
    para(doc,
        "Sputter depth profiles are detected automatically, either from a "
        "Kratos file's own instrument record or from a repeated region in a "
        "VAMAS file with an etch-time variable. Ticking a region folder puts "
        "every level on one panel. The export dialog then offers region-type "
        "checkboxes and level selection (All, First N, Every Nth, or a range)."
    )
    para(doc,
        "Level 0 is the surface at time zero, followed by the cumulative "
        "sputter time. Etch level and etch time appear in the metadata "
        "CSV/PDF and the Details panel, and are written into each VAMAS block "
        "as comment lines."
    )

    # 24. Troubleshooting -------------------------------------------------------
    add_page_break(doc)
    h1(doc, "24. Troubleshooting and notes")
    bullets(doc, [
        "tkinter is part of Python but needs an extra OS package on some "
        "Linux systems: sudo apt-get install python3-tk (Debian/Ubuntu), or "
        "sudo dnf install python3-tkinter (Fedora). The launcher reports "
        "whether it is missing.",
        "Settings (theme, panel sizes, view options, plot style and your "
        "presets) are saved in ~/.spectradeck_config.json. The holder-photo "
        "calibration lives in each workbook; the last one used seeds new "
        "workbooks via ~/.spectradeck_calib.json.",
        "Binding energy is photon energy minus kinetic energy and is not "
        "charge-corrected, so peaks on a charging sample may sit a few eV off "
        "until you calibrate (Chapter 11).",
        "The .experiment, .vgd and .kal readers are reverse-engineered from "
        "undocumented formats. They have been checked against vendor exports "
        "of the same data, but cross-check anything critical against the "
        "vendor's own software.",
        "If a .experiment file was transferred as text rather than binary it "
        "can be silently corrupted; the application detects this and refuses "
        "to export noise.",
        "Some libraries are optional and a feature that needs a missing one "
        "says so instead of failing: h5py (NeXus export, .kfit files), "
        "PyMuPDF (the in-app PDF preview), python-pptx (the slides), Pillow "
        "(icons, camera pictures and cover pictures) and matplotlib (plots).",
        "A Kratos file records when each run started but not when it ended, "
        "so the report’s Timing section is shorter for Kratos data; it is "
        "left out rather than estimated.",
        "To test the application against your own data, set the XPS_CORPUS "
        "environment variable to a folder of spectra files and run the test "
        "suite to check that every recognised file loads.",
    ])

    # Appendices ------------------------------------------------------------
    add_page_break(doc)
    h1(doc, "Appendix A: Supported file formats")
    add_table(doc, FORMATS_HEADERS, FORMATS_ROWS, widths_cm=[4.0, 3.2, 9.4])

    add_page_break(doc)
    h1(doc, "Appendix B: Keyboard shortcuts")
    add_table(doc, ["Shortcut", "Action"], SHORTCUTS, widths_cm=[5.0, 11.6])


# ----------------------------------------------------------------------
# main
# ----------------------------------------------------------------------

def main():
    doc = Document()
    set_page_a4(doc)
    add_footer(doc)

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    build_title_page(doc)
    build_toc(doc)
    build_chapters(doc)

    doc.save(OUTPUT)
    print(f"Wrote {OUTPUT}")
    print(f"Figures placed: {fig_counter['n']}")


if __name__ == "__main__":
    main()
